#!/usr/bin/env bash

VERSION="$1"
GIT_COMMIT=$(git rev-parse HEAD)

if [ "x${VERSION}" == "x" ] ; then
  echo Please specify a version, of the form v0.0.0
  exit 1
fi

if [ "x${GIT_COMMIT}" == "x" ] ; then
  echo Unable to get git commit, but continuing with unknown
  GIT_COMMIT="unknown"
fi

if [ $(git tag -l ${VERSION}) ] ; then
  echo A git tag for ${VERSION} already exists, exiting.
  exit 1
fi

cat <<EOF >version.go
package prme
// This file was auto-generated by the $0 script.
const Version="${VERSION}"
const GitCommit="${GIT_COMMIT}"
EOF
go fmt version.go >/dev/null
git commit -m "Release version ${VERSION}" version.go
if [ $? -gt 0 ] ; then
  exit 1
fi

git tag ${VERSION}
if [ $? -gt 0 ] ; then
  exit 1
fi

echo Since this release process is new, run these commands to actually release:
echo goreleaser --skip-announce --rm-dist
echo git push
